#Deriving the latest base image
FROM python:latest

#Labels as key value pair
LABEL Maintainer="roushan.me17"

#Pip install required libraries
RUN pip install psycopg2-binary
RUN pip install boto3
RUN pip install requests


#Working directory of docker container
WORKDIR /usr/app/src

#Copy the code over to the docker container
COPY updatePublications.py ./


#Instruction to run the script
CMD [ "python", "./updatePublications.py"]